version: '3.0'

services:

  rabbitmq:
    build : ./
    container_name: rabbitmq-server
    image: rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
